--- ### 代码生成器配置
generator:
  # 排除数据表
  excludeTables:
    - DATABASECHANGELOG
    - DATABASECHANGELOGLOCK
    - gen_config
    - gen_field_config
  ## 类型映射
  typeMappings:
    MYSQL:
      Integer:
        - int
        - tinyint
        - smallint
        - mediumint
        - integer
      String:
        - varchar
        - char
        - text
        - mediumtext
        - longtext
        - tinytext
      LocalDate:
        - date
      LocalDateTime:
        - datetime
        - timestamp
      Long:
        - bigint
      Float:
        - float
      Double:
        - double
      BigDecimal:
        - decimal
      Boolean:
        - bit
  ## 模板配置
  templateConfigs:
    DO:
      # 模板路径
      templatePath: Entity.ftl
      # 包名称
      packageName: model.entity
      # 排除字段
      excludeFields:
        - id
        - createUser
        - createTime
        - updateUser
        - updateTime
    Query:
      templatePath: Query.ftl
      packageName: model.query
    Req:
      templatePath: Req.ftl
      packageName: model.req
    Resp:
      templatePath: Resp.ftl
      packageName: model.resp
      excludeFields:
        - id
        - createUser
        - createTime
    DetailResp:
      templatePath: DetailResp.ftl
      packageName: model.resp
      excludeFields:
        - id
        - createUser
        - createTime
        - updateUser
        - updateTime
    Mapper:
      templatePath: Mapper.ftl
      packageName: mapper
    Service:
      templatePath: Service.ftl
      packageName: service
    ServiceImpl:
      templatePath: ServiceImpl.ftl
      packageName: service.impl
    Controller:
      templatePath: Controller.ftl
      packageName: controller